### ISSUE TITLE
Error when running npm run serve

### ISSUE THREAD

**Issue by jwright04** [Garethderioth/backbone-webpack#1]
Received the following error when using the `npm run serve` command: `Error: Cannot find module 'extract-text-webpack-plugin'`

Solution was to add `extract-text-webpack-plugin": "^1.0.1` to the dependencies object (or just run `npm i extract-text-webpack-plugin`).

**Comment by glrodasz** [comment]
Thank you! Tomorrow I will fixed it and I will update the code to the ES6 correct syntax.

**Comment by jwright04** [comment]
No worries!

**Comment by glrodasz** [comment]
@jwright04 I just updated the repository with your fix, the ES6 syntax and a best README file. Thanks again for your help.
